[package]
name = "mr-kaffee-2020-06"
version = "0.1.0"
authors = ["Peter Wieland <peter@die-wielands.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
